#!/usr/bin/env python3

import json
import os
import random
import secrets
import signal
import string
import subprocess
import sys
import time
import urllib.error
import urllib.request
from decimal import Decimal, InvalidOperation, ROUND_DOWN
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = REPO_ROOT / "config"
ENVIRONMENTS_DIR = CONFIG_DIR / "environments"
LOCAL_DIR = REPO_ROOT / ".local"
BINARY_PATH = REPO_ROOT / "build" / "shardeumd"
LOCAL_CONFIG = json.loads((ENVIRONMENTS_DIR / "local.json").read_text())
CHAIN_ID = LOCAL_CONFIG["chain_id"]
BASE_DENOM = LOCAL_CONFIG["base_denom"]
MIN_GAS_PRICE = f"2048130280389041{BASE_DENOM}"
DEFAULT_NODE_COUNT = 10
DECIMAL_FACTOR = 10**18
STAKE_AMOUNT = DECIMAL_FACTOR  # 1 SHM
FUND_AMOUNT = 10000 * DECIMAL_FACTOR  # 10000 SHM to cover stake + multiple high fees
HIGH_FEE = 1024065140194520500000  # 1024.0651401945205 SHM global fee requirement
BECH32_CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"


def run(cmd, **kwargs):
    completed = subprocess.run(cmd, check=False, start_new_session=True, **kwargs)
    if completed.returncode != 0:
        raise RuntimeError(f"Command failed ({completed.returncode}): {' '.join(cmd)}")
    return completed


def run_capture(cmd, **kwargs):
    kwargs.setdefault("text", True)
    completed = subprocess.run(
        cmd,
        check=False,
        start_new_session=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        **kwargs,
    )
    if completed.returncode != 0:
        stdout = (completed.stdout or "").strip()
        stderr = (completed.stderr or "").strip()
        raise RuntimeError(
            f"Command failed ({completed.returncode}): {' '.join(cmd)}\nstdout: {stdout}\nstderr: {stderr}"
        )
    return completed.stdout.strip()


def random_word(min_len=4, max_len=10):
    letters = string.ascii_lowercase
    ln = random.randint(min_len, max_len)
    return ''.join(random.choice(letters) for _ in range(ln))


def random_domain():
    tlds = ["io", "org", "net", "com", "xyz", "zone"]
    return f"https://{random_word(5,10)}.{random.choice(tlds)}"


def random_keybase_identity():
    # Keybase identities are typically <=16 chars alphanumeric
    chars = string.ascii_lowercase + string.digits
    ln = random.randint(8, 16)
    return ''.join(random.choice(chars) for _ in range(ln))


def random_email():
    domains = ["example.com", "validator.net", "shm.dev", "security.io"]
    user = random_word(5, 10)
    return f"{user}@{random.choice(domains)}"


def random_details(node_index):
    rand_tail = secrets.token_hex(4)
    return f"Autogenerated validator description for node{node_index}: {rand_tail}"


def generate_validator_metadata(node_index):
    # Provide all required fields with plausible randomness
    moniker = f"val-node{node_index}-{random_word(4,6)}"
    return {
        "moniker": moniker,
        "website": random_domain(),
        "identity": random_keybase_identity(),
        "security": random_email(),
        "details": random_details(node_index),
    }


def apply_genesis_validator_metadata():
    """Issue an edit-validator tx to enrich node0 (genesis validator) with random metadata.
    Only runs if node0 is up and we haven't already created a metadata file."""
    if not read_pid(0):
        return
    node0_dir = LOCAL_DIR / "node0"
    meta_path = node0_dir / "validator_metadata.json"
    if meta_path.exists():
        # Assume already handled (either from previous run or manual edit)
        return
    print("Applying random metadata to genesis validator (node0)...")
    metadata = generate_validator_metadata(0)
    try:
        meta_path.write_text(json.dumps(metadata, indent=2))
    except Exception:  # pylint: disable=broad-except
        pass
    rpc_port = node_ports(0)["rpc"]
    # Wait briefly for chain to produce first block so staking edits succeed
    start_wait = time.time()
    while time.time() - start_wait < 15:
        h = fetch_height(rpc_port)
        if h and h[0] >= 1:
            break
        time.sleep(1)
    fee_amount = ashm(HIGH_FEE)

    # Detect if --moniker flag is supported (older Cosmos SDK variants omit it for edit-validator)
    supports_moniker = False
    try:
        help_text = run_capture([
            str(BINARY_PATH.resolve()),
            "tx", "staking", "edit-validator", "--help"
        ], cwd=REPO_ROOT)
        if "--moniker" in help_text:
            supports_moniker = True
    except Exception:  # pylint: disable=broad-except
        pass

    cmd = [
        str(BINARY_PATH.resolve()),
        "tx", "staking", "edit-validator",
        "--from", "validator",
        "--home", str(node0_dir),
        "--keyring-backend", "test",
        "--node", f"tcp://127.0.0.1:{rpc_port}",
        "--chain-id", CHAIN_ID,
        "--gas", "500000",
        "--fees", fee_amount,
        "--identity", metadata["identity"],
        "--website", metadata["website"],
        "--security-contact", metadata["security"],
        "--details", metadata["details"],
        "--yes",
    ]
    if supports_moniker:
        cmd.extend(["--moniker", metadata["moniker"]])
    else:
        print("(edit-validator --moniker not supported; leaving moniker as node0)")
    try:
        run(cmd, cwd=REPO_ROOT)
    except RuntimeError as err:
        # If it fails for some transient reason, we won't block the rest of the flow.
        print(f"Warning: edit-validator tx failed: {err}")
    print("Genesis validator metadata applied.")


def ensure_binary():
    if BINARY_PATH.exists():
        return
    print("Building shardeumd binary...")
    run(["make", "build"], cwd=REPO_ROOT)
    if not BINARY_PATH.exists():
        raise RuntimeError("build/shardeumd not found after make build")


def start_network(node_count=DEFAULT_NODE_COUNT):
    ensure_binary()
    env = os.environ.copy()
    env["SHARDEUM_CONFIG_DIR"] = str(CONFIG_DIR.resolve())
    env["SHARDEUM_NETWORK"] = "local"
    env["SHARDEUM_CHAIN_ID"] = CHAIN_ID
    env["BINARY"] = str(BINARY_PATH.resolve())
    env["SKIP_BUILD"] = "1"
    cmd = ["./scripts/start_network.sh", "--network", "local", "--nodes", str(node_count)]
    print(f"Starting local network with {node_count} nodes...")
    LOCAL_DIR.mkdir(exist_ok=True)
    bootstrap_log = LOCAL_DIR / "bootstrap.log"
    with open(bootstrap_log, "ab") as log_file:
        log_file.write(f"\n=== start_network {time.strftime('%Y-%m-%d %H:%M:%S')} ===\n".encode())
        process = subprocess.Popen(
            cmd,
            cwd=REPO_ROOT,
            env=env,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

    waited = 0
    while waited < 60:
        if node_pid_path(0).exists():
            time.sleep(2)
            print("Local network reported ready. Returning to menu.")
            print(f"Bootstrap output logged to {bootstrap_log}")
            try:
                apply_genesis_validator_metadata()
            except Exception as err:  # pylint: disable=broad-except
                print(f"Warning: could not apply genesis validator metadata: {err}")
            return
        if process.poll() is not None:
            raise RuntimeError(f"start_network.sh exited with code {process.returncode}; see {bootstrap_log}")
        time.sleep(1)
        waited += 1

    print("Node0 pid not detected yet; bootstrap script still running in background.")
    print(f"Check {bootstrap_log} for progress (process pid {process.pid}).")


def stop_network():
    node_dirs = sorted(LOCAL_DIR.glob("node*"))
    if not node_dirs:
        print("No local nodes found.")
        return
    for node_dir in node_dirs:
        idx = int(node_dir.name.replace("node", ""))
        stop_node(idx, silent=True)
    print("All local nodes signalled to stop.")


def node_pid_path(index):
    return LOCAL_DIR / f"node{index}" / "node.pid"


def node_log_path(index):
    return LOCAL_DIR / f"node{index}" / "node.log"


def pid_alive(pid):
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def read_pid(index):
    path = node_pid_path(index)
    if not path.exists():
        return None
    try:
        pid = int(path.read_text().strip())
    except ValueError:
        return None
    return pid if pid_alive(pid) else None


def stop_node(index, silent=False):
    node_dir = LOCAL_DIR / f"node{index}"
    if not node_dir.exists():
        if not silent:
            print(f"Node {index} directory not found at {node_dir}.")
        return
    pid = read_pid(index)
    if not pid:
        if not silent:
            print(f"Node {index} is not running.")
        return
    if not silent:
        print(f"Stopping node {index} (pid {pid})...")
    try:
        os.kill(pid, signal.SIGTERM)
    except OSError as err:
        if not silent:
            print(f"  Failed to signal node {index}: {err}")
        return
    deadline = time.time() + 10
    while time.time() < deadline:
        if not pid_alive(pid):
            break
        time.sleep(0.5)
    if pid_alive(pid):
        if not silent:
            print(f"  Node {index} did not exit; sending SIGKILL.")
        try:
            os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
    pid_file = node_pid_path(index)
    if pid_file.exists():
        pid_file.unlink()
    if not silent:
        print(f"Node {index} stopped.")


def node_ports(index):
    return {
        "rpc": 26657 + index,
        "p2p": 27656 + index,
        "grpc": 9090 + index,
        "api": 1317 + index,
        "json": 8545 + index * 2,
        "ws": 8546 + index * 2,
    }


def start_node(index):
    ensure_binary()
    node_dir = LOCAL_DIR / f"node{index}"
    if not node_dir.exists():
        print(f"Node {index} directory does not exist. Start the full network first.")
        return
    if read_pid(index):
        print(f"Node {index} appears to be running already.")
        return
    ports = node_ports(index)
    node_type = "validator" if index == 0 else "full-node"
    cmd = [
        str(BINARY_PATH.resolve()),
        "start",
        "--home",
        str(node_dir),
        "--chain-id",
        CHAIN_ID,
        "--rpc.laddr",
        f"tcp://127.0.0.1:{ports['rpc']}",
        "--p2p.laddr",
        f"tcp://0.0.0.0:{ports['p2p']}",
        "--grpc.address",
        f"localhost:{ports['grpc']}",
        "--minimum-gas-prices",
        MIN_GAS_PRICE,
        "--pruning",
        "nothing",
    ]
    if index == 0:
        # Enable REST API for node0
        cmd.extend([
            "--api.enable",
        ])
    else:
        cmd.extend([
            "--json-rpc.enable",
            "--json-rpc.address",
            f"127.0.0.1:{ports['json']}",
            "--json-rpc.ws-address",
            f"127.0.0.1:{ports['ws']}",
            "--json-rpc.api",
            "eth,txpool,personal,net,debug,web3",
        ])
    env = os.environ.copy()
    env["SHARDEUM_CONFIG_DIR"] = str(CONFIG_DIR.resolve())
    env["SHARDEUM_NETWORK"] = "local"
    env["SHARDEUM_CHAIN_ID"] = CHAIN_ID
    log_path = node_log_path(index)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with open(log_path, "ab") as log_file:
        process = subprocess.Popen(
            cmd,
            cwd=REPO_ROOT,
            env=env,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    node_pid_path(index).write_text(str(process.pid))
    print(f"Node {index} ({node_type}) started with pid {process.pid}.")


def list_nodes():
    if not LOCAL_DIR.exists():
        print("No local network data found. Start the network first.")
        return
    node_indices = sorted(int(p.name.replace("node", "")) for p in LOCAL_DIR.glob("node*") if p.is_dir())
    if not node_indices:
        print("No node directories found under .local.")
        return
    print("Node status:")
    for idx in node_indices:
        pid = read_pid(idx)
        ports = node_ports(idx)
        status = "running" if pid else "stopped"
        extra = f"rpc={ports['rpc']}"
        print(f"  node{idx}: {status} {extra}")


def fetch_height(port):
    url = f"http://127.0.0.1:{port}/status"
    try:
        with urllib.request.urlopen(url, timeout=2) as resp:
            data = json.loads(resp.read())
    except (urllib.error.URLError, TimeoutError, ConnectionError):
        return None
    except ValueError:
        return None
    try:
        info = data["result"]["sync_info"]
        return int(info["latest_block_height"]), info.get("latest_block_time", "")
    except (KeyError, TypeError, ValueError):
        return None


def monitor_blocks(duration=20):
    print(f"Monitoring block height for ~{duration} seconds...")
    end_time = time.time() + duration
    try:
        while time.time() < end_time:
            row = time.strftime("%H:%M:%S")
            node_entries = []
            for node_dir in sorted(LOCAL_DIR.glob("node*")):
                idx = int(node_dir.name.replace("node", ""))
                if not read_pid(idx):
                    continue
                height = fetch_height(node_ports(idx)["rpc"])
                if height:
                    node_entries.append(f"node{idx}:{height[0]}")
            if node_entries:
                print(f"[{row}] " + " ".join(node_entries))
            else:
                print(f"[{row}] no running RPC endpoints detected")
            time.sleep(2)
    except KeyboardInterrupt:
        print("\nMonitoring interrupted.")
    finally:
        print("Returning to menu.")


def ashm(amount_int):
    return f"{amount_int}{BASE_DENOM}"


def format_shm(amount_int):
    value = Decimal(amount_int) / Decimal(DECIMAL_FACTOR)
    text = format(value, 'f')
    if '.' in text:
        text = text.rstrip('0').rstrip('.')
    return text or "0"


def bech32_polymod(values):
    generator = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3]
    chk = 1
    for value in values:
        top = chk >> 25
        chk = (chk & 0x1FFFFFF) << 5 ^ value
        for i in range(5):
            if ((top >> i) & 1) != 0:
                chk ^= generator[i]
    return chk


def bech32_hrp_expand(hrp):
    return [ord(c) >> 5 for c in hrp] + [0] + [ord(c) & 31 for c in hrp]


def bech32_create_checksum(hrp, data):
    values = bech32_hrp_expand(hrp) + data
    polymod = bech32_polymod(values + [0, 0, 0, 0, 0, 0]) ^ 1
    return [(polymod >> 5 * (5 - i)) & 31 for i in range(6)]


def bech32_encode(hrp, data):
    combined = data + bech32_create_checksum(hrp, data)
    return hrp + '1' + ''.join(BECH32_CHARSET[d] for d in combined)


def bech32_decode(bech):
    if any(ord(x) < 33 or ord(x) > 126 for x in bech):
        return None, None
    bech = bech.strip()
    if bech.lower() != bech and bech.upper() != bech:
        return None, None
    bech = bech.lower()
    pos = bech.rfind('1')
    if pos < 1 or pos + 7 > len(bech):
        return None, None
    hrp = bech[:pos]
    data_chars = bech[pos + 1 :]
    data = [BECH32_CHARSET.find(c) for c in data_chars]
    if -1 in data:
        return None, None
    if bech32_polymod(bech32_hrp_expand(hrp) + data) != 1:
        return None, None
    return hrp, data[:-6]


def get_balance(address, rpc_port):
    try:
        output = run_capture(
            [
                str(BINARY_PATH.resolve()),
                "query",
                "bank",
                "balances",
                address,
                "--node",
                f"tcp://127.0.0.1:{rpc_port}",
                "-o",
                "json",
            ],
            cwd=REPO_ROOT,
        )
    except RuntimeError as err:
        print(f"Balance query failed: {err}")
        return None

    try:
        data = json.loads(output)
    except json.JSONDecodeError:
        print("Unable to parse balance response.")
        return None

    balances = data.get("balances", [])
    for entry in balances:
        if entry.get("denom") == BASE_DENOM:
            try:
                return int(entry.get("amount", "0"))
            except ValueError:
                return None
    return 0


def ensure_funds(address, target_rpc_port, required):
    balance = get_balance(address, target_rpc_port)
    if balance is None:
        return None
    if balance >= required:
        return balance
    if not read_pid(0):
        print("node0 must be running to top up accounts.")
        return balance
    print("Funding validator account...")
    rpc_port = node_ports(0)["rpc"]
    fund_amount = ashm(FUND_AMOUNT)
    fee_amount = ashm(HIGH_FEE)
    run(
        [
            str(BINARY_PATH.resolve()),
            "tx",
            "bank",
            "send",
            "validator",
            address,
            fund_amount,
            "--from",
            "validator",
            "--home",
            str(LOCAL_DIR / "node0"),
            "--keyring-backend",
            "test",
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "--chain-id",
            CHAIN_ID,
            "--gas",
            "500000",
            "--fees",
            fee_amount,
            "--yes",
        ],
        cwd=REPO_ROOT,
    )

    time.sleep(3)
    return get_balance(address, target_rpc_port)


def parse_shm_amount(raw):
    if raw is None:
        return None
    try:
        value = Decimal(str(raw).strip())
    except (InvalidOperation, ValueError):
        return None
    if value <= 0:
        return None
    scaled = (value * Decimal(DECIMAL_FACTOR)).to_integral_value(rounding=ROUND_DOWN)
    if scaled == 0:
        return None
    return int(scaled)


def prompt_amount(prompt_text, default_shm):
    default_str = str(default_shm)
    while True:
        raw = input(f"{prompt_text} [{default_str}]: ").strip()
        if not raw:
            raw = default_str
        amount = parse_shm_amount(raw)
        if amount:
            return amount
        print("Enter a numeric amount greater than zero (e.g., 1 or 0.5).")


def get_validator_addresses(index, create_key=False):
    node_dir = LOCAL_DIR / f"node{index}"
    if not node_dir.exists():
        print(f"node{index} directory not found at {node_dir}.")
        return None
    # Special-case node0: its genesis validator key is named 'validator'
    if index == 0:
        validator_key = "validator"
    else:
        validator_key = f"validator-node{index}"
    try:
        run_capture(
            [
                str(BINARY_PATH.resolve()),
                "keys",
                "show",
                validator_key,
                "--keyring-backend",
                "test",
                "--home",
                str(node_dir),
            ],
            cwd=REPO_ROOT,
        )
    except RuntimeError:
        if not create_key:
            print(f"Validator key '{validator_key}' not found. Promote node{index} first.")
            return None
        print(f"Creating validator key '{validator_key}' on node{index}...")
        run(
            [
                str(BINARY_PATH.resolve()),
                "keys",
                "add",
                validator_key,
                "--keyring-backend",
                "test",
                "--home",
                str(node_dir),
            ],
            cwd=REPO_ROOT,
        )

    account_addr = run_capture(
        [
            str(BINARY_PATH.resolve()),
            "keys",
            "show",
            validator_key,
            "--keyring-backend",
            "test",
            "--home",
            str(node_dir),
            "-a",
        ],
        cwd=REPO_ROOT,
    )
    hrp, data = bech32_decode(account_addr)
    if hrp is None or data is None:
        print("Failed to decode validator account address; cannot derive operator address.")
        return None
    valoper_addr = bech32_encode("shardeumvaloper", data)
    return node_dir, validator_key, account_addr, valoper_addr


def get_delegation_tokens(delegator_addr, validator_addr, rpc_port):
    try:
        output = run_capture(
            [
                str(BINARY_PATH.resolve()),
                "query",
                "staking",
                "delegation",
                delegator_addr,
                validator_addr,
                "--node",
                f"tcp://127.0.0.1:{rpc_port}",
                "-o",
                "json",
            ],
            cwd=REPO_ROOT,
        )
    except RuntimeError:
        # try legacy CLI output (text)
        try:
            output = run_capture(
                [
                    str(BINARY_PATH.resolve()),
                    "query",
                    "staking",
                    "delegation",
                    delegator_addr,
                    validator_addr,
                    "--node",
                    f"tcp://127.0.0.1:{rpc_port}",
                ],
                cwd=REPO_ROOT,
            )
        except RuntimeError:
            return 0

    try:
        data = json.loads(output)
        if isinstance(data, dict):
            balance = None
            if "balance" in data:
                balance = data.get("balance")
            elif "delegation_response" in data:
                balance = (
                    data.get("delegation_response", {})
                    .get("balance")
                )
            if balance is not None:
                amount = None
                if isinstance(balance, dict):
                    amount = balance.get("amount")
                elif isinstance(balance, str):
                    amount = balance
                if amount is not None:
                    return int(amount)
        return 0
    except (json.JSONDecodeError, TypeError, ValueError):
        # fallback to regex on text output
        import re

        match = re.search(r"balance:\s*(\d+)", output)
        if match:
            try:
                return int(match.group(1))
            except ValueError:
                return 0
        match = re.search(r"amount:\s*\"?(\d+)", output)
        if match:
            try:
                return int(match.group(1))
            except ValueError:
                return 0
        return 0


def show_voting_power():
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to query validator set.")
        return

    rpc_port = node_ports(0)["rpc"]
    try:
        output = run_capture(
            [
                str(BINARY_PATH.resolve()),
                "query",
                "staking",
                "validators",
                "--node",
                f"tcp://127.0.0.1:{rpc_port}",
                "-o",
                "json",
            ],
            cwd=REPO_ROOT,
        )
    except RuntimeError as err:
        print(f"Validator query failed: {err}")
        return

    try:
        data = json.loads(output)
    except json.JSONDecodeError:
        print("Unable to parse validator set response.")
        return

    validators = data.get("validators", [])
    if not validators:
        print("No active validators reported.")
        return

    # Build mapping of validator addresses to local node indices
    local_nodes = {}
    for node_dir in LOCAL_DIR.glob("node*"):
        if node_dir.is_dir():
            index = int(node_dir.name.replace("node", ""))
            info = get_validator_addresses(index, create_key=False)
            if info:
                _, _, _, valoper_addr = info
                local_nodes[valoper_addr] = index

    total_power = 0
    records = []
    for val in validators:
        power = int(val.get("tokens", "0"))
        moniker = val.get("description", {}).get("moniker", "")
        val_addr = val.get("operator_address", "")
        
        # Add node index if this is a local node
        node_info = ""
        if val_addr in local_nodes:
            node_index = local_nodes[val_addr]
            is_running = "running" if read_pid(node_index) else "stopped"
            node_info = f" [node{node_index} - {is_running}]"
        
        records.append((moniker, val_addr, power, node_info))
        total_power += power

    records.sort(key=lambda item: item[2], reverse=True)
    print("Validators:")
    for moniker, val_addr, power, node_info in records:
        percent = (power / total_power * 100) if total_power else 0
        if val_addr in local_nodes:
            node_index = local_nodes[val_addr]
            is_running = "running" if read_pid(node_index) else "stopped"
            print(f"  node{node_index:2d} {moniker:15s} ({is_running}) power={power} ({percent:.2f}%)")
        else:
            print(f"  ----  {moniker:15s} (external)    power={power} ({percent:.2f}%)")
    print(f"Total voting power: {total_power}")


def promote_node_to_validator():
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to fund new validators.")
        return

    index = prompt_int("Node index to promote", 1)
    if index <= 0:
        print("node0 is already a validator; choose node index >= 1.")
        return

    if not read_pid(index):
        print(f"node{index} is not running. Start it before promoting.")
        return

    info = get_validator_addresses(index, create_key=True)
    if not info:
        return

    node_dir, validator_key, address, _ = info
    print(f"Validator account: {address}")

    rpc_port = node_ports(0)["rpc"]
    target_rpc_port = node_ports(index)["rpc"]

    required = STAKE_AMOUNT + HIGH_FEE
    balance = ensure_funds(address, target_rpc_port, required)
    if balance is None:
        print("Unable to confirm funding; aborting promotion.")
        return
    print(f"Account balance: {balance} {BASE_DENOM}")
    if balance < required:
        print(
            "Balance appears insufficient after funding. Check transactions before retrying."
        )
        return

    # Generate random but sensible metadata for dashboard visibility
    metadata = generate_validator_metadata(index)
    print("Submitting create-validator transaction with metadata:")
    for k, v in metadata.items():
        print(f"  {k}: {v}")

    # Persist metadata file so subsequent scripts / queries can read it (mirrors add_node.sh behavior)
    node_metadata_path = node_dir / "validator_metadata.json"
    try:
        node_metadata_path.write_text(json.dumps(metadata, indent=2))
    except Exception as write_err:  # pylint: disable=broad-except
        print(f"Warning: failed to write metadata file {node_metadata_path}: {write_err}")

    env = os.environ.copy()
    env["BINARY"] = str(BINARY_PATH.resolve())
    env.setdefault("SHARDEUM_NETWORK", "local")
    cmd = [
        "./scripts/create_validator.sh",
        f"node{index}",
        "--validator-key",
        validator_key,
        "--network",
        "local",
        "--moniker",
        metadata["moniker"],
        "--website",
        metadata["website"],
        "--identity",
        metadata["identity"],
        "--security",
        metadata["security"],
        "--details",
        metadata["details"],
    ]
    run(cmd, cwd=REPO_ROOT, env=env)

    print(f"node{index} promoted to validator (stake {ashm(STAKE_AMOUNT)}) with metadata.")


def increase_validator_stake():
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to submit staking transactions.")
        return

    index = prompt_int("Validator node index", 0)
    if index < 0:
        print("Node index must be non-negative.")
        return

    if not read_pid(index):
        print(f"node{index} is not running. Start it before adjusting stake.")
        return

    info = get_validator_addresses(index, create_key=False)
    if not info:
        return

    node_dir, validator_key, account_addr, valoper_addr = info
    amount = prompt_amount("Additional stake (SHM)", 1)
    network_rpc = node_ports(0)["rpc"]
    required = amount + HIGH_FEE
    balance = ensure_funds(account_addr, network_rpc, required)
    if balance is None:
        print("Unable to confirm balance; aborting delegation.")
        return
    if balance < required:
        print("Insufficient balance after funding attempt; retry with smaller amount.")
        return

    print(f"Delegating {format_shm(amount)} SHM to validator node{index}...")
    run(
        [
            str(BINARY_PATH.resolve()),
            "tx",
            "staking",
            "delegate",
            valoper_addr,
            ashm(amount),
            "--from",
            validator_key,
            "--home",
            str(node_dir),
            "--keyring-backend",
            "test",
            "--node",
            f"tcp://127.0.0.1:{network_rpc}",
            "--chain-id",
            CHAIN_ID,
            "--gas",
            "500000",
            "--fees",
            ashm(HIGH_FEE),
            "--yes",
        ],
        cwd=REPO_ROOT,
    )
    print("Additional stake delegated successfully.")


def decrease_validator_stake():
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to submit staking transactions.")
        return

    index = prompt_int("Validator node index", 0)
    if index < 0:
        print("Node index must be non-negative.")
        return

    info = get_validator_addresses(index, create_key=False)
    if not info:
        return

    node_dir, validator_key, account_addr, valoper_addr = info
    network_rpc = node_ports(0)["rpc"]
    current = get_delegation_tokens(account_addr, valoper_addr, network_rpc)
    if current <= 0:
        print("No active delegation found for this validator.")
        return

    print(f"Current bonded stake: {format_shm(current)} SHM")
    amount = prompt_amount("Amount to unbond (SHM)", 1)
    if amount > current:
        print("Cannot unbond more than the current bonded stake.")
        return

    print(f"Unbonding {format_shm(amount)} SHM from validator node{index}...")
    run(
        [
            str(BINARY_PATH.resolve()),
            "tx",
            "staking",
            "unbond",
            valoper_addr,
            ashm(amount),
            "--from",
            validator_key,
            "--home",
            str(node_dir),
            "--keyring-backend",
            "test",
            "--node",
            f"tcp://127.0.0.1:{network_rpc}",
            "--chain-id",
            CHAIN_ID,
            "--gas",
            "500000",
            "--fees",
            ashm(HIGH_FEE),
            "--yes",
        ],
        cwd=REPO_ROOT,
    )
    print("Unbond transaction submitted. Funds will become liquid after the unbonding period.")


def show_validator_metadata():
    """Show on-chain validator description metadata plus any local metadata files."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to query validators.")
        return
    rpc_port = node_ports(0)["rpc"]
    try:
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query",
            "staking",
            "validators",
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "-o",
            "json",
        ], cwd=REPO_ROOT)
    except RuntimeError as err:
        print(f"Failed to query validators: {err}")
        return
    try:
        data = json.loads(output)
    except json.JSONDecodeError:
        print("Could not parse validator JSON.")
        return
    validators = data.get("validators", [])
    if not validators:
        print("No validators found on-chain.")
        return
    print("On-chain validator metadata:")
    for val in validators:
        desc = val.get("description", {})
        op = val.get("operator_address", "")
        print(f"  {desc.get('moniker','')} ({op})")
        print(f"    website : {desc.get('website','')}")
        print(f"    identity: {desc.get('identity','')}")
        print(f"    security: {desc.get('security_contact','')}")
        print(f"    details : {desc.get('details','')}")
    # Local metadata files
    print("\nLocal validator_metadata.json files:")
    for node_dir in sorted(LOCAL_DIR.glob("node*")):
        meta_file = node_dir / "validator_metadata.json"
        if meta_file.exists():
            try:
                meta = json.loads(meta_file.read_text() or '{}')
            except json.JSONDecodeError:
                print(f"  {node_dir.name}: invalid JSON")
                continue
            print(f"  {node_dir.name} -> moniker={meta.get('moniker','')} website={meta.get('website','')} identity={meta.get('identity','')} security={meta.get('security','')} details={meta.get('details','')}")
        else:
            print(f"  {node_dir.name}: (no metadata file)")


def random_edit_validator_metadata():
    """Interactively choose a validator node and edit one or several metadata fields via edit-validator.
    'ALL' option updates all non-moniker fields; moniker can be updated separately if supported."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running.")
        return
    # Query current validators
    rpc_port = node_ports(0)["rpc"]
    try:
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query", "staking", "validators",
            "--node", f"tcp://127.0.0.1:{rpc_port}",
            "-o", "json",
        ], cwd=REPO_ROOT)
    except RuntimeError as err:
        print(f"Failed to query validators: {err}")
        return
    try:
        validators = json.loads(output).get("validators", [])
    except json.JSONDecodeError:
        print("Could not parse validators JSON")
        return
    if not validators:
        print("No validators on-chain.")
        return
    # Build map of node index -> (validator_key, valoper_addr)
    valoper_set = {v.get("operator_address"): v for v in validators if v.get("operator_address")}
    validator_nodes = {}
    for node_dir in sorted(LOCAL_DIR.glob("node*")):
        try:
            idx = int(node_dir.name.replace("node", ""))
        except ValueError:
            continue
        info = get_validator_addresses(idx, create_key=False)
        if not info:
            continue
        _, validator_key, _, valoper_addr = info
        if valoper_addr in valoper_set:
            validator_nodes[idx] = (validator_key, valoper_addr)
    if not validator_nodes:
        print("No local validator nodes found on-chain.")
        return
    print("Available validator nodes:")
    for idx, (vkey, _) in sorted(validator_nodes.items()):
        print(f"  node{idx} (key {vkey})")
    raw_idx = input("Enter node index to edit (blank to cancel): ").strip()
    if not raw_idx:
        print("Cancelled.")
        return
    try:
        idx = int(raw_idx)
    except ValueError:
        print("Invalid index.")
        return
    if idx not in validator_nodes:
        print(f"node{idx} is not recognized as an active validator.")
        return
    validator_key, _valoper_addr = validator_nodes[idx]
    node_dir = LOCAL_DIR / f"node{idx}"
    print(f"Editing validator node{idx} (key {validator_key})")
    # Determine supported flags
    supports_moniker = False
    try:
        help_text = run_capture([
            str(BINARY_PATH.resolve()),
            "tx", "staking", "edit-validator", "--help"
        ], cwd=REPO_ROOT)
        if "--moniker" in help_text:
            supports_moniker = True
    except Exception:  # pylint: disable=broad-except
        pass
    # Prompt for field choice
    print("Choose metadata field to randomize (node{idx}):")
    print("  1. moniker" + (" (supported)" if supports_moniker else " (unsupported in this build)"))
    print("  2. website")
    print("  3. identity")
    print("  4. security contact")
    print("  5. details")
    print("  6. ALL (website, identity, security, details — excludes moniker)")
    print("  7. Cancel")
    choice = input("Select: ").strip()
    if choice == "7" or choice == "":
        print("Cancelled.")
        return
    new_meta = generate_validator_metadata(idx)
    # Load existing file (if any) so we only overwrite chosen fields
    meta_path = node_dir / "validator_metadata.json"
    if meta_path.exists():
        try:
            current_meta = json.loads(meta_path.read_text() or '{}')
        except json.JSONDecodeError:
            current_meta = {}
    else:
        current_meta = {}
    # Determine fields to update
    fields = []
    if choice == "1":
        if not supports_moniker:
            print("Moniker update not supported by this binary.")
            return
        fields = ["moniker"]
    elif choice == "2":
        fields = ["website"]
    elif choice == "3":
        fields = ["identity"]
    elif choice == "4":
        fields = ["security"]
    elif choice == "5":
        fields = ["details"]
    elif choice == "6":
        fields = ["website", "identity", "security", "details"]
    else:
        print("Unknown selection.")
        return
    for f in fields:
        current_meta[f] = new_meta[f]
    # Write back metadata file
    try:
        meta_path.write_text(json.dumps(current_meta, indent=2))
    except Exception as err:  # pylint: disable=broad-except
        print(f"Warning: could not update metadata file: {err}")
    rpc_port = node_ports(0)["rpc"]  # use node0 RPC for tx broadcast
    fee_amount = ashm(HIGH_FEE)
    cmd = [
        str(BINARY_PATH.resolve()),
        "tx", "staking", "edit-validator",
        "--from", validator_key if idx != 0 else "validator",
        "--home", str(node_dir),
        "--keyring-backend", "test",
        "--node", f"tcp://127.0.0.1:{rpc_port}",
        "--chain-id", CHAIN_ID,
        "--gas", "500000",
        "--fees", fee_amount,
        "--yes",
    ]
    # Append field flags
    flag_map = {
        "website": ("--website", current_meta.get("website", "")),
        "identity": ("--identity", current_meta.get("identity", "")),
        "security": ("--security-contact", current_meta.get("security", "")),
        "details": ("--details", current_meta.get("details", "")),
        "moniker": ("--moniker", current_meta.get("moniker", "")),
    }
    for f in fields:
        flag, val = flag_map[f]
        cmd.extend([flag, val])
    # If moniker not being updated, we still must include at least one other flag (already ensured)
    try:
        print("Submitting edit-validator tx with fields:", ", ".join(fields))
        run(cmd, cwd=REPO_ROOT)
        print("Metadata update transaction submitted.")
    except RuntimeError as err:
        print(f"Failed to submit edit-validator tx: {err}")
def get_validator_consensus_address(index):
    """Get the consensus address for a validator node."""
    node_dir = LOCAL_DIR / f"node{index}"
    priv_validator_key = node_dir / "config" / "priv_validator_key.json"
    
    if not priv_validator_key.exists():
        print(f"Validator key file not found: {priv_validator_key}")
        return None
    
    try:
        with open(priv_validator_key, 'r') as f:
            key_data = json.load(f)
        
        # Extract the consensus address directly from the validator key file
        # This is the hex-encoded consensus address
        hex_address = key_data.get("address", "")
        if not hex_address:
            print("Consensus address not found in validator key file")
            return None
            
        # Convert hex address to bech32 consensus address
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "debug",
            "addr",
            hex_address
        ], cwd=REPO_ROOT)
        
        # Parse the output to extract the consensus address
        for line in output.split('\n'):
            if line.startswith('Bech32 Con:'):
                return line.split(':', 1)[1].strip()
        
        print("Could not find consensus address in debug output")
        return None
    except Exception as e:
        print(f"Error getting consensus address: {e}")
        return None


def get_signing_info(cons_address, rpc_port):
    """Get signing info for a validator using the slashing query."""
    try:
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query",
            "slashing",
            "signing-info",
            cons_address,
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "-o",
            "json"
        ], cwd=REPO_ROOT)
        
        data = json.loads(output)
        return data
    except Exception as e:
        print(f"Error querying signing info: {e}")
        return None


def is_node_validator(index):
    """Check if a node is actually a validator by querying the validator set."""
    if not read_pid(0):
        return False
    
    info = get_validator_addresses(index, create_key=False)
    if not info:
        return False
    
    _, _, _, valoper_addr = info
    rpc_port = node_ports(0)["rpc"]
    
    try:
        # Check if validator exists in the validator set
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query",
            "staking",
            "validator",
            valoper_addr,
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "-o",
            "json"
        ], cwd=REPO_ROOT)
        
        data = json.loads(output)
        validator = data.get("validator", {})
        status = validator.get("status", "")
        
        # Check if validator is bonded (active)
        return status == "BOND_STATUS_BONDED"
    except:
        return False


def test_slashing_double_sign():
    """Test double-sign slashing by copying validator keys to create duplicate signing."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to test double-sign slashing.")
        return

    # Find an active validator to use as source (exclude node0)
    source_index = None
    print("🔍 Searching for active validators...")
    
    for i in range(1, 10):  # Check nodes 1-9 (skip node0)
        if is_node_validator(i):
            source_index = i
            print(f"✅ Found active validator: node{i}")
            break
    
    if source_index is None:
        print("❌ No active validators found (excluding node0).")
        print("Use option 9 to promote some nodes to validators first.")
        return
    
    index = source_index  # Use the found validator
    
    # Get source validator info
    source_info = get_validator_addresses(index, create_key=False)
    if not source_info:
        print(f"❌ node{index} does not have validator keys configured.")
        return

    # Find an available target node (should be running but not a validator)
    target_index = None
    print("🔍 Searching for running non-validator nodes...")
    
    for i in range(10):  # Check nodes 0-9
        if i == index or i == 0:  # Skip source node and bootstrap validator
            continue
        if read_pid(i):  # Node is running
            if not is_node_validator(i):  # Not an active validator
                target_index = i
                print(f"✅ Found running non-validator: node{i}")
                break
            else:
                print(f"⚠️  node{i} is running but already a validator (skipped)")
        else:
            print(f"📴 node{i} is not running (skipped)")
    
    if target_index is None:
        print("❌ Could not find a suitable target node for double-sign test.")
        print("Need a running non-validator node. Try starting more nodes first.")
        print("💡 Tip: Use option 6 to start additional nodes")
        return

    source_node_dir = LOCAL_DIR / f"node{index}"
    target_node_dir = LOCAL_DIR / f"node{target_index}"
    
    source_key_file = source_node_dir / "config" / "priv_validator_key.json"
    target_key_file = target_node_dir / "config" / "priv_validator_key.json"
    backup_key_file = target_node_dir / "config" / "priv_validator_key.json.backup"
    
    if not source_key_file.exists():
        print(f"❌ Source validator key not found: {source_key_file}")
        return
    
    print(f"🔥 Setting up double-sign scenario:")
    print(f"   Source validator: node{index} (active validator)")
    print(f"   Target node: node{target_index} (will copy keys to)")
    print(f"   Expected penalty: 5% stake slash + permanent jailing")
    
    rpc_port = node_ports(0)["rpc"]
    
    # Get initial validator info
    _, _, _, valoper_addr = source_info
    cons_address = get_validator_consensus_address(index)
    
    if not cons_address:
        print("❌ Failed to get consensus address")
        return
    
    try:
        # Get initial stake
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query",
            "staking",
            "validator",
            valoper_addr,
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "-o",
            "json"
        ], cwd=REPO_ROOT)
        
        import json as json_lib
        validator_data = json_lib.loads(output)
        initial_tokens = int(validator_data.get("validator", {}).get("tokens", "0"))
        
        print(f"\nInitial validator state:")
        print(f"  Operator: {valoper_addr}")
        print(f"  Consensus: {cons_address}")
        print(f"  Initial stake: {format_shm(initial_tokens)} SHM")
        
    except Exception as e:
        print(f"❌ Error getting initial validator info: {e}")
        return
    
    # Backup original target key if it exists
    if target_key_file.exists():
        print(f"\n📋 Backing up original key from node{target_index}...")
        import shutil
        shutil.copy2(target_key_file, backup_key_file)
    
    # Copy validator key to target node
    print(f"🔑 Copying validator key from node{index} to node{target_index}...")
    import shutil
    shutil.copy2(source_key_file, target_key_file)
    
    print(f"✅ Key copied successfully!")
    
    # Restart target node to load the new key
    print(f"🔄 Restarting node{target_index} to load the new validator key...")
    stop_node(target_index, silent=True)
    time.sleep(2)  # Brief pause between stop and start
    start_node(target_index)
    
    # Wait for node to start and sync
    print(f"⏳ Waiting for node{target_index} to restart and sync...")
    time.sleep(5)
    
    print(f"\n⚠️  WARNING: Both node{index} and node{target_index} now have the same validator key!")
    print(f"This will cause double-signing when both nodes attempt to sign blocks.")
    
    # Verify target node is syncing
    target_rpc_port = node_ports(target_index)["rpc"]
    print(f"\n🔄 Checking if node{target_index} is syncing...")
    
    target_height = None
    for attempt in range(5):
        target_height_info = fetch_height(target_rpc_port)
        if target_height_info:
            target_height = target_height_info[0]
            print(f"✅ node{target_index} is syncing at height {target_height}")
            break
        else:
            print(f"⏳ Waiting for node{target_index} to sync... (attempt {attempt + 1}/5)")
            time.sleep(2)
    
    if target_height is None:
        print(f"❌ node{target_index} is not responding or not syncing properly")
        print(f"Double-sign test may not work correctly")
    
    # Get current height before starting double-sign
    height_info = fetch_height(rpc_port)
    start_height = height_info[0] if height_info else 0
    
    print(f"\nStarting double-sign monitoring at height {start_height}...")
    print(f"Both nodes will now compete to sign the same blocks, triggering slashing.")
    print(f"Expected result: Validator will be slashed 5% and permanently jailed.")
    print(f"⚠️  Note: Double-signing detection may take several minutes due to:")
    print(f"    - Evidence collection and ABCI processing delays")
    print(f"    - Consensus layer needs to detect conflicting signatures")
    print(f"    - Evidence submission can take up to the unbonding period")
    print(f"\nPress Ctrl+C to stop monitoring and clean up.\n")
    
    try:
        check_interval = 5
        max_wait_time = 300  # 5 minutes maximum wait
        start_time = time.time()
        
        while time.time() - start_time < max_wait_time:
            # Get current height and validator status
            height_info = fetch_height(rpc_port)
            current_height = height_info[0] if height_info else "unknown"
            
            print(f"[{time.strftime('%H:%M:%S')}] Height: {current_height}")
            
            # Check validator status
            try:
                output = run_capture([
                    str(BINARY_PATH.resolve()),
                    "query",
                    "staking",
                    "validator",
                    valoper_addr,
                    "--node",
                    f"tcp://127.0.0.1:{rpc_port}",
                    "-o",
                    "json"
                ], cwd=REPO_ROOT)
                
                validator_data = json_lib.loads(output)
                validator = validator_data.get("validator", {})
                current_tokens = int(validator.get("tokens", "0"))
                jailed = validator.get("jailed", False)
                status = validator.get("status", "")
                
                # Check for slashing
                if current_tokens < initial_tokens:
                    slashed_amount = initial_tokens - current_tokens
                    slash_percent = (slashed_amount / initial_tokens) * 100
                    
                    print(f"\n🔴 DOUBLE-SIGN SLASHING DETECTED! 🔴")
                    print(f"Initial stake: {format_shm(initial_tokens)} SHM")
                    print(f"Current stake: {format_shm(current_tokens)} SHM")
                    print(f"Slashed amount: {format_shm(slashed_amount)} SHM ({slash_percent:.1f}%)")
                    print(f"Jailed: {'YES' if jailed else 'NO'}")
                    print(f"Status: {status}")
                    
                    # Check signing info for tombstone status
                    signing_info = get_signing_info(cons_address, rpc_port)
                    if signing_info:
                        val_info = signing_info.get("val_signing_info", {})
                        tombstoned = val_info.get("tombstoned", False)
                        if tombstoned:
                            print(f"🪦 TOMBSTONED: Validator permanently removed (cannot unjail)")
                        else:
                            print(f"⚠️  Jailed but not tombstoned")
                    
                    print(f"\n✅ Double-sign slashing test completed successfully!")
                    break
                else:
                    print(f"  Stake: {format_shm(current_tokens)} SHM (no slashing yet)")
                    print(f"  Jailed: {'YES' if jailed else 'NO'}")
                    print(f"  Status: {status}")
                    
            except Exception as e:
                print(f"  Error checking validator: {e}")
            
            time.sleep(check_interval)
        
        # If we reach here, the timeout was reached
        elapsed_time = int(time.time() - start_time)
        print(f"\n⏰ Timeout reached after {elapsed_time} seconds")
        print(f"Double-signing evidence may still be pending in the consensus layer.")
        print(f"Consider:")
        print(f"  1. Checking logs for evidence submission")  
        print(f"  2. Waiting longer (evidence can take up to unbonding period)")
        print(f"  3. Trying with a more aggressive validator setup")
            
    except KeyboardInterrupt:
        print(f"\n⏹️  Monitoring stopped by user.")
    
    finally:
        # Clean up: restore original key
        print(f"\n🧹 Cleaning up...")
        if backup_key_file.exists():
            print(f"Restoring original key to node{target_index}...")
            shutil.copy2(backup_key_file, target_key_file)
            backup_key_file.unlink()
        else:
            print(f"Removing copied key from node{target_index}...")
            if target_key_file.exists():
                target_key_file.unlink()
        
        print(f"✅ Cleanup completed. node{target_index} restored to non-validator state.")


def test_slashing_downtime():
    """Test downtime slashing by stopping a validator node and monitoring for jailing."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to test slashing.")
        return

    index = prompt_int("Validator node index to test slashing", 1)
    if index <= 0:
        print("Cannot test slashing on node0 (bootstrap validator). Choose index >= 1.")
        return
    
    if not read_pid(index):
        print(f"node{index} is not running. Start it first.")
        return

    # Check if node is actually a validator
    if not is_node_validator(index):
        print(f"❌ node{index} is not an active validator!")
        print(f"To promote node{index} to validator:")
        print(f"  1. Use menu option 9 (Promote node to validator)")
        print(f"  2. Select node index {index}")
        print(f"  3. Wait for the promotion to complete")
        print(f"  4. Then return here to test slashing")
        return

    # Get validator info
    info = get_validator_addresses(index, create_key=False)
    if not info:
        return
    
    node_dir, validator_key, account_addr, valoper_addr = info
    rpc_port = node_ports(0)["rpc"]
    
    # Get consensus address
    cons_address = get_validator_consensus_address(index)
    if not cons_address:
        print("Failed to get consensus address for validator")
        return
    
    print(f"✅ Testing downtime slashing for validator node{index}")
    print(f"Validator operator: {valoper_addr}")
    print(f"Consensus address: {cons_address}")
    
    # Get initial signing info
    initial_info = get_signing_info(cons_address, rpc_port)
    if not initial_info:
        print("❌ Failed to get initial signing info")
        print("This shouldn't happen for an active validator. The validator may have just been created.")
        print("Wait a few blocks for the signing info to be initialized, then try again.")
        return
    
    val_info = initial_info.get("val_signing_info", {})
    print(f"Initial state:")
    print(f"  Jailed until: {val_info.get('jailed_until', 'N/A')}")
    print(f"  Missed blocks: {val_info.get('missed_blocks_counter', 0)}")
    print(f"  Start height: {val_info.get('start_height', 0)}")
    
    # Stop the validator to trigger downtime
    print(f"\nStopping node{index} to trigger downtime...")
    stop_node(index, silent=False)
    
    # Monitor for slashing
    print("\nMonitoring for downtime slashing (this may take several minutes)...")
    print("The validator will be jailed when it misses enough blocks.")
    print("Press Ctrl+C to stop monitoring and return to menu.\n")
    
    missed_blocks_threshold = 34560 * 0.95  # 95% of signed_blocks_window
    check_interval = 10  # seconds
    
    try:
        while True:
            # Get current height and signing info
            height_info = fetch_height(rpc_port)
            if height_info:
                current_height = height_info[0]
                print(f"Current height: {current_height}")
            
            signing_info = get_signing_info(cons_address, rpc_port)
            if signing_info:
                val_info = signing_info.get("val_signing_info", {})
                missed_blocks = val_info.get("missed_blocks_counter", 0)
                jailed_until = val_info.get("jailed_until", "")
                
                print(f"Missed blocks: {missed_blocks}")
                
                # Check if validator is jailed
                if jailed_until and jailed_until != "1970-01-01T00:00:00Z":
                    print(f"\n🔴 VALIDATOR JAILED! 🔴")
                    print(f"Jailed until: {jailed_until}")
                    print(f"Missed blocks at jailing: {missed_blocks}")
                    
                    # Test unjailing after jail period
                    print("\nWaiting for jail period to expire...")
                    from datetime import datetime
                    try:
                        jail_time = datetime.fromisoformat(jailed_until.replace('Z', '+00:00'))
                        current_time = datetime.now(jail_time.tzinfo)
                        
                        if current_time >= jail_time:
                            print("Jail period has expired. Attempting to unjail...")
                            test_unjail_validator(index, cons_address)
                        else:
                            wait_seconds = int((jail_time - current_time).total_seconds())
                            print(f"Need to wait {wait_seconds} more seconds before unjailing")
                    except Exception as e:
                        print(f"Error parsing jail time: {e}")
                    
                    break
                
                missed_blocks_int = int(missed_blocks) if isinstance(missed_blocks, str) else missed_blocks
                if missed_blocks_int > missed_blocks_threshold * 0.8:
                    print(f"⚠️  Approaching slashing threshold (missed {missed_blocks_int} blocks)")
            
            time.sleep(check_interval)
            
    except KeyboardInterrupt:
        print("\nMonitoring stopped by user.")
    
    print(f"\nRestart node{index} to resume validation:")
    print(f"  python3 scripts/local_testomatic.py -> option 6 -> {index}")


def test_unjail_validator(index, cons_address):
    """Test unjailing a validator after downtime slashing."""
    info = get_validator_addresses(index, create_key=False)
    if not info:
        return
    
    node_dir, validator_key, account_addr, valoper_addr = info
    network_rpc = node_ports(0)["rpc"]
    
    print(f"Attempting to unjail validator node{index}...")
    
    try:
        run([
            str(BINARY_PATH.resolve()),
            "tx",
            "slashing",
            "unjail",
            "--from",
            validator_key,
            "--home",
            str(node_dir),
            "--keyring-backend",
            "test",
            "--node",
            f"tcp://127.0.0.1:{network_rpc}",
            "--chain-id",
            CHAIN_ID,
            "--gas",
            "500000",
            "--fees",
            ashm(HIGH_FEE),
            "--yes"
        ], cwd=REPO_ROOT)
        
        print("✅ Unjail transaction submitted successfully!")
        
        # Verify unjailing after a few blocks
        time.sleep(10)
        signing_info = get_signing_info(cons_address, network_rpc)
        if signing_info:
            val_info = signing_info.get("val_signing_info", {})
            jailed_until = val_info.get("jailed_until", "")
            
            if jailed_until == "1970-01-01T00:00:00Z":
                print("✅ Validator successfully unjailed!")
            else:
                print(f"⚠️  Validator still appears jailed until: {jailed_until}")
        
    except Exception as e:
        print(f"❌ Failed to unjail validator: {e}")


def show_slashing_params():
    """Display the current slashing parameters."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to query slashing parameters.")
        return
    
    rpc_port = node_ports(0)["rpc"]
    
    try:
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query",
            "slashing",
            "params",
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "-o",
            "json"
        ], cwd=REPO_ROOT)
        
        data = json.loads(output)
        params = data.get("params", {})
        
        print("Current Slashing Parameters:")
        print(f"  Signed blocks window: {params.get('signed_blocks_window', 'N/A')}")
        print(f"  Min signed per window: {params.get('min_signed_per_window', 'N/A')}")
        print(f"  Downtime jail duration: {params.get('downtime_jail_duration', 'N/A')}")
        print(f"  Slash fraction (double sign): {params.get('slash_fraction_double_sign', 'N/A')}")
        print(f"  Slash fraction (downtime): {params.get('slash_fraction_downtime', 'N/A')}")
        
        # Calculate practical thresholds
        window = int(params.get('signed_blocks_window', 34560))
        min_signed = float(params.get('min_signed_per_window', 0.05))
        max_missed = int(window * (1 - min_signed))
        
        print(f"\nPractical Thresholds:")
        print(f"  Max blocks that can be missed: {max_missed} out of {window}")
        print(f"  Blocks needed to avoid jailing: {window - max_missed}")
        
    except Exception as e:
        print(f"Error querying slashing parameters: {e}")



def check_node_slashing_status():
    """Check slashing status for a specific node."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to query slashing status.")
        return
    
    index = prompt_int("Node index to check", 1)
    
    # Check if node has validator keys (might be jailed, so don't check if active)
    info = get_validator_addresses(index, create_key=False)
    if not info:
        print(f"❌ node{index} does not have validator keys configured.")
        return
    
    rpc_port = node_ports(0)["rpc"]
    
    # Get consensus address and signing info
    cons_address = get_validator_consensus_address(index)
    if not cons_address:
        print("Failed to get consensus address for validator")
        return
    
    _, _, _, valoper_addr = info
    
    print(f"Slashing Status for node{index}")
    print("=" * 50)
    print(f"Consensus address: {cons_address}")
    print(f"Validator operator: {valoper_addr}")
    
    # Get current height
    height_info = fetch_height(rpc_port)
    current_height = height_info[0] if height_info else "unknown"
    print(f"Current block height: {current_height}")
    
    # Check validator status in staking module
    try:
        output = run_capture([
            str(BINARY_PATH.resolve()),
            "query",
            "staking",
            "validator",
            valoper_addr,
            "--node",
            f"tcp://127.0.0.1:{rpc_port}",
            "-o",
            "json"
        ], cwd=REPO_ROOT)
        
        import json as json_lib
        validator_data = json_lib.loads(output)
        validator = validator_data.get("validator", {})
        status = validator.get("status", "")
        tokens = validator.get("tokens", "0")
        jailed = validator.get("jailed", False)
        
        print(f"\nValidator Status:")
        if status == "BOND_STATUS_BONDED":
            print(f"  🟢 BONDED (Active)")
        elif status == "BOND_STATUS_UNBONDING":
            print(f"  🟡 UNBONDING")
        elif status == "BOND_STATUS_UNBONDED":
            print(f"  🔴 UNBONDED")
        else:
            print(f"  ❓ {status}")
        
        print(f"  Jailed: {'🔴 YES' if jailed else '✅ NO'}")
        print(f"  Tokens: {format_shm(int(tokens))} SHM")
        
    except Exception as e:
        print(f"\nValidator Status: ❌ Could not query validator info")
        print(f"  This might indicate the validator was never created or has been removed")
    
    # Get signing info
    signing_info = get_signing_info(cons_address, rpc_port)
    if not signing_info:
        print("❌ Failed to get signing info")
        return
    
    val_info = signing_info.get("val_signing_info", {})
    missed_blocks = int(val_info.get("missed_blocks_counter", 0))
    jailed_until = val_info.get("jailed_until", "")
    start_height = val_info.get("start_height", 0)
    
    # Check if jailed
    is_jailed = jailed_until and jailed_until != "1970-01-01T00:00:00Z"
    
    print(f"\nSigning Performance:")
    print(f"  Start height: {start_height}")
    print(f"  Missed blocks: {missed_blocks}")
    
    # Calculate thresholds
    window = 34560  # signed_blocks_window
    max_missed = int(window * 0.95)  # Can miss 95% of blocks
    
    print(f"  Max blocks can miss: {max_missed}")
    print(f"  Blocks until jailing: {max_missed - missed_blocks}")
    
    # Progress bar
    progress = missed_blocks / max_missed if max_missed > 0 else 0
    progress_percent = progress * 100
    
    if progress < 0.5:
        status = "✅ HEALTHY"
    elif progress < 0.8:
        status = "⚠️  APPROACHING THRESHOLD"
    elif progress < 1.0:
        status = "🔶 DANGER - CLOSE TO SLASHING"
    else:
        status = "🔴 SHOULD BE JAILED"
    
    print(f"  Progress to slashing: {progress_percent:.1f}%")
    print(f"  Status: {status}")
    
    # Jail status
    print(f"\nJail Status:")
    if is_jailed:
        print(f"  🔴 JAILED until: {jailed_until}")
        
        # Check if jail period has expired
        from datetime import datetime
        try:
            jail_time = datetime.fromisoformat(jailed_until.replace('Z', '+00:00'))
            current_time = datetime.now(jail_time.tzinfo)
            
            if current_time >= jail_time:
                print("  ✅ Jail period has expired - can unjail now")
            else:
                wait_seconds = int((jail_time - current_time).total_seconds())
                print(f"  ⏰ Must wait {wait_seconds} more seconds before unjailing")
        except Exception as e:
            print(f"  ❓ Error parsing jail time: {e}")
    else:
        print("  ✅ Not jailed")
    
    # Node status
    is_running = read_pid(index)
    print(f"\nNode Status:")
    print(f"  Process: {'🟢 Running' if is_running else '🔴 Stopped'}")
    
    if not is_running:
        print(f"  💡 Tip: While stopped, this validator will continue missing blocks")
        print(f"       and approach the slashing threshold.")


def monitor_validator_signing():
    """Monitor signing info for all validators showing slashing-relevant metrics."""
    ensure_binary()
    if not read_pid(0):
        print("node0 must be running to monitor validators.")
        return
    
    duration = prompt_int("Monitor duration (seconds)", 60)
    rpc_port = node_ports(0)["rpc"]
    
    print(f"Monitoring validator signing for {duration} seconds...")
    print("Shows: Height | Missed Blocks | Jail Status | Node Status")
    print("Press Ctrl+C to stop early.\n")
    
    # Build mapping of validator addresses to local node indices
    local_nodes = {}
    for node_dir in LOCAL_DIR.glob("node*"):
        if node_dir.is_dir():
            index = int(node_dir.name.replace("node", ""))
            info = get_validator_addresses(index, create_key=False)
            if info:
                _, _, _, valoper_addr = info
                local_nodes[valoper_addr] = index
    
    end_time = time.time() + duration
    
    try:
        while time.time() < end_time:
            # Get current block height
            height_info = fetch_height(rpc_port)
            current_height = height_info[0] if height_info else "unknown"
            
            print(f"[{time.strftime('%H:%M:%S')}] Block Height: {current_height}")
            
            # Get all validators
            try:
                output = run_capture([
                    str(BINARY_PATH.resolve()),
                    "query",
                    "staking",
                    "validators",
                    "--node",
                    f"tcp://127.0.0.1:{rpc_port}",
                    "-o",
                    "json"
                ], cwd=REPO_ROOT)
                
                data = json.loads(output)
                validators = data.get("validators", [])
                
                for val in validators:
                    moniker = val.get("description", {}).get("moniker", "unknown")
                    operator_addr = val.get("operator_address", "")
                    
                    # Get node index if this is a local validator
                    node_index = local_nodes.get(operator_addr)
                    node_status = ""
                    if node_index is not None:
                        is_running = read_pid(node_index)
                        node_status = f"node{node_index}:{'ON' if is_running else 'OFF'}"
                    else:
                        node_status = "external"
                    
                    # Get consensus address and signing info
                    try:
                        if node_index is not None:
                            cons_address = get_validator_consensus_address(node_index)
                            if cons_address:
                                signing_info = get_signing_info(cons_address, rpc_port)
                                if signing_info:
                                    val_info = signing_info.get("val_signing_info", {})
                                    missed_blocks = val_info.get("missed_blocks_counter", 0)
                                    jailed_until = val_info.get("jailed_until", "")
                                    
                                    # Ensure missed_blocks is an integer
                                    missed_blocks_int = int(missed_blocks) if isinstance(missed_blocks, str) else missed_blocks
                                    
                                    # Check if jailed
                                    is_jailed = jailed_until and jailed_until != "1970-01-01T00:00:00Z"
                                    jail_status = "JAILED" if is_jailed else "active"
                                    
                                    # Calculate approach to slashing threshold
                                    threshold = 34560 * 0.95  # 95% of signed_blocks_window
                                    if missed_blocks_int > threshold * 0.5:
                                        status_icon = "⚠️"
                                    elif missed_blocks_int > threshold * 0.8:
                                        status_icon = "🔶"
                                    elif is_jailed:
                                        status_icon = "🔴"
                                    else:
                                        status_icon = "✅"
                                    
                                    print(f"  {status_icon} {moniker:15s} | missed:{missed_blocks_int:5d} | {jail_status:6s} | {node_status}")
                                else:
                                    print(f"  ❓ {moniker:15s} | missed:  N/A | no info | {node_status}")
                            else:
                                print(f"  ❓ {moniker:15s} | missed:  N/A | no cons | {node_status}")
                        else:
                            print(f"  ⚫ {moniker:15s} | missed:  N/A | external | {node_status}")
                            
                    except Exception as e:
                        print(f"  ❌ {moniker:15s} | missed:  ERR | error   | {node_status}")
                
                print()
                
            except Exception as e:
                print(f"Error monitoring validators: {e}")
            
            time.sleep(5)
            
    except KeyboardInterrupt:
        print("\nMonitoring stopped by user.")
    
    print("\nLegend:")
    print("  ✅ = Healthy validator")
    print("  ⚠️  = Approaching slashing threshold (>50% of max missed blocks)")
    print("  🔶 = Close to slashing threshold (>80% of max missed blocks)")
    print("  🔴 = Validator is jailed")
    print("  ❓ = Unable to get signing info")
    print("  ⚫ = External validator")
    print("  ❌ = Error querying validator")
    print("\nReturning to menu.")

def prompt_int(prompt, default):
    raw = input(f"{prompt} [{default}]: ").strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        print("Invalid number; using default.")
        return default


def main():
    actions = {
        "1": ("Build shardeumd binary", lambda: ensure_binary() or print("Binary ready.")),
        "2": ("Start local network", lambda: start_network(prompt_int("Number of nodes", DEFAULT_NODE_COUNT))),
        "3": ("Stop entire network", stop_network),
        "4": ("Show node status", list_nodes),
        "5": ("Stop a node", lambda: stop_node(prompt_int("Node index", 0))),
        "6": ("Start a node", lambda: start_node(prompt_int("Node index", 0))),
        "7": ("Monitor block height", monitor_blocks),
        "8": ("Show validator voting power", show_voting_power),
        "9": ("Promote node to validator", promote_node_to_validator),
        "10": ("Increase validator stake", increase_validator_stake),
        "11": ("Decrease validator stake", decrease_validator_stake),
        "12": ("Show validator metadata", show_validator_metadata),
        "13": ("Random edit validator metadata", random_edit_validator_metadata),
        "14": ("Test downtime slashing", test_slashing_downtime),
        "15": ("Test double-sign slashing", test_slashing_double_sign),
        "16": ("Check node slashing status", check_node_slashing_status),
        "17": ("Show slashing parameters", show_slashing_params),
        "18": ("Monitor validator signing", monitor_validator_signing),
        "19": ("Exit", None),
    }

    while True:
        print("\nLocal Testomatic Menu")
        for key, (desc, _) in actions.items():
            print(f"  {key}. {desc}")
        choice = input("Select option: ").strip()
        if choice == "19":
            print("Goodbye.")
            return
        action = actions.get(choice)
        if not action:
            print("Unknown option.")
            continue
        _, func = action
        try:
            func()
        except KeyboardInterrupt:
            print("\nOperation interrupted by user.")
        except Exception as err:  # pylint: disable=broad-except
            print(f"Error: {err}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nExiting.")
        sys.exit(0)
