name: ci

on:
  push:
    branches: [ dev, ci-fix ]
  pull_request:
    branches: [ dev ]

jobs:
  QA-merge-checks:
    name: QA merge checks
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "CI passed successfully"
